data_dir=$1

/nlsasfs/home/ai4bharat/yashkm/miniconda3/envs/itd/bin/fairseq-train ${data_dir}/final_bin \
    --task translation \
    --max-source-positions 256 \
    --max-target-positions 256 \
    --max-update 1000000 \
    --save-interval-updates 2500 \
    --arch transformer_base18L \
    --criterion label_smoothed_cross_entropy \
    --source-lang SRC \
    --target-lang TGT \
    --lr-scheduler inverse_sqrt \
    --label-smoothing 0.1 \
    --optimizer adam \
    --adam-betas "(0.9, 0.98)" \
    --clip-norm 1.0 \
    --warmup-init-lr 1e-07 \
    --lr 0.0007 \
    --warmup-updates 4000 \
    --dropout 0.2 \
    --save-dir ${data_dir}/base18L_7e-4 \
    --save-interval 1 \
    --keep-interval-updates 1 \
    --no-epoch-checkpoints \
    --patience 10 \
    --skip-invalid-size-inputs-valid-test \
    --memory-efficient-fp16 \
    --update-freq 4 \
    --distributed-world-size 8 \
    --num-workers 24 \
    --max-tokens 8192 \
    --eval-bleu \
    --eval-bleu-args "{\"beam\": 5, \"lenpen\": 1.0, \"max_len_a\": 1.2, \"max_len_b\": 10}" \
    --eval-bleu-detok moses \
    --eval-bleu-remove-bpe sentencepiece \
    --eval-bleu-print-samples \
    --best-checkpoint-metric bleu \
    --maximize-best-checkpoint-metric
