backend: "python"
max_batch_size: 512
input [{
  name: "INPUT_TEXT"
  data_type: TYPE_STRING
  dims: 1
},
{
  name: "INPUT_LANGUAGE_ID"
  data_type: TYPE_STRING
  dims: 1
},
{
  name: "OUTPUT_LANGUAGE_ID"
  data_type: TYPE_STRING
  dims: 1
}]
  
output {
  name: "OUTPUT_TEXT"
  data_type: TYPE_STRING
  dims: 1
}

dynamic_batching { 
  
}

instance_group [{
 count: 1
 kind: KIND_GPU
}]
