$schema: https://azuremlschemas.azureedge.net/latest/managedOnlineDeployment.schema.json
name: ai4b-indictransv2--t4-piv--gpu
endpoint_name: ai4b-indictransv2--t4
model: azureml:indictrans-v2--models:1
model_mount_path: /models
environment: azureml:triton-indictrans-v2-env:1
instance_type: Standard_NC4as_T4_v3
instance_count: 1
request_settings:
  request_timeout_ms: 90000
  max_concurrent_requests_per_instance: 100
  max_queue_wait_ms: 2000
app_insights_enabled: true
