$schema: https://azuremlschemas.azureedge.net/latest/environment.schema.json
name: triton-indictrans-v2-env
image: dhruvaprod.azurecr.io/nmt/triton-indictrans-v2:latest
version: 1
inference_config:
  liveness_route:
    path: /v2/health/live
    port: 8000
  readiness_route:
    path: /v2/health/ready
    port: 8000
  scoring_route:
    path: /
    port: 8000
